### ISSUE TITLE
Add all model entities to Django admin

### ISSUE THREAD

**Issue by pinarpink** [elixir-luxembourg/daisy#102]
**Is your feature request related to a problem? Please describe.**

We use Django admin to assist reporting over DAISY. Not all model entities have been added to the admin, e.g. Storage Locations

**Describe the solution requested**

Add all model entities to django admin.

**Describe possible alternatives**

Have a reporting  feature in DAISY
https://github.com/elixir-luxembourg/daisy/issues/99

**Other info context**

**Comment by jLebioda** [comment]
Addressed in https://github.com/elixir-luxembourg/daisy/tree/102-add-all-models-to-admin
