### ISSUE TITLE
Add Data Declaration selection to Storage definition

### ISSUE THREAD

**Issue by pinarpink** [elixir-luxembourg/daisy#12]
When defining storage records for a Dataset, it should be possible to (optionally) select which Data Declarations are stored where.

When a Data Declaration is selected the data types within that declaration should automatically be carried forward into the form for creating a Storage.

**Comment by vildead** [comment]
@pinarpink selecting Data Declaration is possible but its data types are not carried forward.

**Comment by pinarpink** [comment]
@vildead yes, I'm aware.  
The data declaration AND data type selection in storage definition is too redundant.  Imo,  users will just  refer to a data declaration or sometimes not refer to any, meaning entire dataset is in the storage. 
Shall we consider putting in a control, which checks the data types in the storage (if specified) with data types of data declaration (if specified)?
What do you think?

**Comment by pinarpink** [comment]
@vildead  I think we can close this for now. If we receive any additional user requests on validation rules, we can re-open.

**Comment by vildead** [comment]
closing the issue for know on commit 425fc268cf69a491767617d0b4bfe5562158c988
