### ISSUE TITLE
Add hints to login page about credentials

### ISSUE THREAD

**Issue by evescat** [elixir-luxembourg/daisy#134]
Currently on login page there is no information how to login or request an account.    
Please add a hint information in login filed with user's uni email.
<img width="555" alt="Screen Shot 2020-02-28 at 17 13 30" src="https://user-images.githubusercontent.com/52324846/75565559-724fc200-5a4e-11ea-8fa2-ef4a1dce209b.png">

**Comment by vildead** [comment]
This feature is already implemented [here](https://github.com/elixir-luxembourg/daisy/blob/51525707610faf01bbb536b89da5ebba8095913d/elixir_daisy/settings.py#L311). 

But there are two related issues:
1. The elixir_daisy/settings.py is not in .gitignore and thus it gets refreshed on every pull of new version. Either should this global variable got to settings_local.py or be set (not left blank)
2. Even after updating the value and restarting all services it does not work.
