### ISSUE TITLE
adjust border display (SAFARI)

### ISSUE THREAD

**Issue by evescat** [elixir-luxembourg/daisy#137]
In case the text is long, it is not wrapped but extends the paragraph border.

![Screen Shot 2020-03-05 at 14 57 56](https://user-images.githubusercontent.com/52324846/76067393-8f751b00-5f8f-11ea-8680-93eeadd90321.png)

**Comment by jLebioda** [comment]
This has been fixed in 1.3.0 (latest stable release); The version of DAISY-demo is 1.1.0
