### ISSUE TITLE
Track Ethics status for cohorts/projects run by collaboration partners

### ISSUE THREAD

**Issue by vildead** [elixir-luxembourg/daisy#139]
Ethics approvals are now recorded using fields **Has National/Institutional Ethics Approval?**
Issues:
1. the default value in database is FALSE which might be a bit misleading when making direct SQL export (here FALSE can stand for both - It has no ethics approval OR field was not populated)
2. Sometimes, Ethics approval is on the partners side. This should be an option to choose.

Solution might be 2 (or 3) checkboxes 
 * **Has Ethics approval**
 * **Partner has Ethics approval** -> which partner?
 * (**Does not have Ethics approval**))

Since the Ethics approval is very important document, a note might be required for all options.

**Comment by pinarpink** [comment]
@vildead  the fact that the partner has ethics approval can be kept on the Cohort entity, not on the dataset entity. Partner's ethics approval has no help for our processing of a dataset.

**Comment by pinarpink** [comment]
Done with https://github.com/elixir-luxembourg/daisy/commit/0f60f83c86fdbb65b3ecd06347d0de53f61e1870
