### ISSUE TITLE
Add Data Declaration selection to Share/Transfer definition

### ISSUE THREAD

**Issue by pinarpink** [elixir-luxembourg/daisy#14]
When defining share/transfer records for a Dataset, it should be possible to (optionally) select which Data Declarations are being transferred.

**Comment by pinarpink** [comment]
Fixed with af163a7 - Merge branch 'feature/Add-Data-Declaration-selection-to-Share-definition-#14' into develop

**Comment by vildead** [comment]
closing the issue. Data declaration was added as "Scope of transfer" field in Transfer edit/create.
Verified on commit:  
425fc268cf69a491767617d0b4bfe5562158c988
