### ISSUE TITLE
Accession number should be unique

### ISSUE THREAD

**Issue by pinarpink** [elixir-luxembourg/daisy#142]
**Describe the bug (current behaviour)**

Several problems with the accession number field. It is defined as not nullable and with a default value of "-".  
As a result when new partners/cohorts are added but not published they all get the accession number of "-". 

This field should be nullable, without a default value. An entity should receive an accession number only when it is published.

**To reproduce**

1. Go to http://daisy.lcsb.uni.lu/api/partners
2. Partners with acronym "EURICE" and "FIBAO-GENYO" have the same accession number of "-"

**Expected behavior**

All partners delivered from the api endpoint should have a unique accession number.

**Environment:**

 - Deployment: daisy.lcsb.uni.lu
 - Version 1.2.0
 
 
**Additional information (error logs, screenshots)**

**Comment by vildead** [comment]
it will be solved by indetifier service
