### ISSUE TITLE
adding a new contract with custodian non-PI is available

### ISSUE THREAD

**Issue by evescat** [elixir-luxembourg/daisy#149]
**Describe the bug (current behaviour)**

Adding the new contract allows to choose as a custodian not a PI. 
See image below, ewa.smula (standard user) is assigned as custodian. 

**To reproduce**

1.  to go CONTRACTS
2. add new Contract with local custodian not PI

**Expected behavior**
Access denied, warning displayed

 - Deployment: [https://10.240.6.75/]
 - Version [1.2.0]

 
 
<img width="1130" alt="Screen Shot 2020-04-15 at 15 31 18" src="https://user-images.githubusercontent.com/52324846/79343119-4c16b080-7f2e-11ea-8fae-0b22700064b1.png">

**Comment by vildead** [comment]
This is expected behaviour. 

Local custodian is a person responsible for the record in Daisy. 

Local custodians of a linked project have still permission to access and edit the contract (permissions are inherited).
