### ISSUE TITLE
Update pg package URL in deployment instructions

### ISSUE THREAD

**Issue by pinarpink** [elixir-luxembourg/daisy#151]
**Describe the bug (current behaviour)**

The following command in **deployment.md** no longer works as packages have moved

`sudo yum install https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-centos10-10-2.noarch.rpm`

**Expected behavior**

In deployment instructions, provide link to [postgres package url builder](https://www.postgresql.org/download/linux/redhat/) to allow deployer to find correct url.

**Environment:**

 - Deployment: https://10.240.16.89/
 - Version [e.g. 1.2.0]
 - Browser [e.g. Firefox 68.x]
 
 
**Additional information (error logs, screenshots)**

**Comment by vildead** [comment]
fixed by #182
