### ISSUE TITLE
Add delete confirmation dialogs.

### ISSUE THREAD

**Issue by pinarpink** [elixir-luxembourg/daisy#18]

**Comment by pinarpink** [comment]
@neoflex  can you please have a look at  branch  https://github.com/elixir-luxembourg/daisy/tree/Add-delete-confirmation-dialogs-%2318
Added confirm dialog, meanwhile   replaced the removal ".deletable" parents with page reload. This allowed the messages from the deletion action to not displayed. 

Are you OK with this?

**Comment by vildead** [comment]
closing the issue. Verified on commit: c4014c78bf9ee50c15a23297169d9d985da38d24
