### ISSUE TITLE
Extend Data declarations to record Legal Basis 

### ISSUE THREAD

**Issue by pinarpink** [elixir-luxembourg/daisy#19]
For a Data Declaration the user should be able to create multiple triples of the following form
(Legal Bases, Categories of Personal data, Remarks).

**Legal Bases is a multi select with the following options:**

- Consent (6.1(a))
- Performance of a contract to which the data subject is party(6.1(b))
- Compliance with a legal obligation to which the controller is subject (6.1(c))
- Protection the vital interests of the data subject (6.1(d))
- Public interest (6.1(e))
- Legitimate interest (6.1(f))

**Categories of Personal data is multi select with the following options:**

- Standard personal data
- Special category, i.e. sensitive, personal data
- Racial or ethnic origin
- Genetic data
- Biometric data for the purpose of uniquely identifying a natural person
- Data concerning health
- Data concerning a natural person’s sex life or sexual orientation
- Data relating to criminal convictions and offences
- Other special categories of data (e.g. molecular data that can give indication on a person's health)

**Remarks** if a free text field

**Comment by vildead** [comment]
At this moment, both dropdown lists are empty - database tables are also empty.

**Comment by pinarpink** [comment]
@vildead @neoflex You need load initial data  in the update script. Can be verified after https://github.com/elixir-luxembourg/daisy/tree/feature/Update-Instructions-need-to-be-documented-(Docker-and-CentOS)-%2347. is merged

**Comment by vildead** [comment]
closing the issue. Verified on commit: e593f75187cf88d0c3d7c36fc990cc920704d716
