### ISSUE TITLE
500 Internal Server Error when uploading attachment to contract

### ISSUE THREAD

**Issue by pinarpink** [elixir-luxembourg/daisy#191]
**Describe the bug (current behaviour)**
I get a 500 error when trying to upload a contract pdf.

**To reproduce**

1. go to https://daisy.lcsb.uni.lu/datasets/
2. select Alex Skupin from local custodians
3. Select the "task force" project 
4. View the only contract under this project
5. Try uploading any attachment.

**Expected behavior**

Document should be uploaded.

**Environment:**

 - Deployment: daisy production deployment at the LCSB
 - Version 1.4.0
 - Browser Safari
 
 
**Additional information (error logs, screenshots)**

**Comment by neoflex** [comment]
the owner of /var/lib/nginx was changed (Probably when nginx is updated)
As a result, the daisy user (running nginx) cannot write temporary files.
to fix:

```
chown -R daisy:daisy /var/lib/nginx
```

**Comment by pinarpink** [comment]
yes, it must be the updates. thanks for the very quick response @neoflex

**Comment by pinarpink** [comment]
This was not a software issue but a deployment VM issue, therefore closing.
