### ISSUE TITLE
DAISY Export does not contain Data Declaration details

### ISSUE THREAD

**Issue by pinarpink** [elixir-luxembourg/daisy#194]
The current JSON export that we get from DAISY does not contain details on the data declaration  including the definitions in the "Data Use Restrictions" section. The export should also include the [DUO term](https://github.com/EBISPOT/DUO) annotations per restriction.

**Comment by jLebioda** [comment]
For the dataset JSON export, the execution chain goes like this:

1. `core/management/commands/export_datasets.py`: lines 21-22
     
     ```
     exp = DatasetsExporter()
     exp.export_to_file(json_file)
     ```
     
2. `core/importer/datasets_exporter.py`: lines 30-34

```
datasets = Dataset.objects.all()
for dataset in datasets:
    ...
    pd = dataset.to_dict()
```

3. `core/models/dataset.py`: line 140:

```
            "data_declarations": [ddec.to_dict() for ddec in self.data_declarations.all()],
```

4.  `core/models/data_declaration.py`: method `to_dict(self)` at line 191:
```
    def to_dict(self):

        base_dict = {
            "title": self.title,
            "data_types":[ dt.name for dt in list(self.data_types)],
            "access_category": self.share_category.name if self.share_category else None,
            "subjects_category": self.subjects_category.name if self.subjects_category else None,
            "de_identification":  self.deidentification_method.name  if self.deidentification_method else None,
            "consent_status":  self.consent_status.name if self.consent_status else None,
            "has_special_subjects": self.has_special_subjects,
            "special_subjects_description": self.special_subjects_description,
            "embargo_date": self.embargo_date.strftime('%Y-%m-%d') if self.embargo_date else None,
            "storage_end_date": self.end_of_storage_duration.strftime('%Y-%m-%d') if self.end_of_storage_duration else None,
            "storage_duration_criteria": self.storage_duration_criteria if self.storage_duration_criteria else None
        }

        return base_dict
```

The dictionary from point 4 above needs to be extended with Data Use Restrictions + DUO terms, and other fields (if they are missing)

**Comment by pinarpink** [comment]
@jLebioda correct. The rEST endpoint also uses `to_dict` to expose the info. We can discuss the extensions to the entities in our call on 18 Dec 2pm.

**Comment by vildead** [comment]
fixed in !203

**Comment by pinarpink** [comment]
released with https://github.com/elixir-luxembourg/daisy/commit/0f60f83c86fdbb65b3ecd06347d0de53f61e1870
