### ISSUE TITLE
The sources of a Data declaration should be editable post-creation.

### ISSUE THREAD

**Issue by pinarpink** [elixir-luxembourg/daisy#20]
the contract and data declaration fields in the "Data Source" section of the Data Declaration form should be editable. See attached screenshot.

![source_contract](https://user-images.githubusercontent.com/2318344/59555888-2b05cc00-8fba-11e9-9e3c-9e38776e03e8.png)

**Comment by vildead** [comment]
I am getting "Server Error (500)"  on 309fd6b620425dd4b0de0cefc23851ccb38fd97b

**Comment by pinarpink** [comment]
@vildead  can you try the merge commit 0f14e83 - Merge branch 'develop' of github.com:elixir-luxembourg/daisy into develop

**Comment by vildead** [comment]
@pinarpink maybe it was my mistake. I have logged in as Alice and I am still getting "**Server Error (500)**" but if I am connected as admin, I can edit the data source.

**Comment by vildead** [comment]
@pinarpink  data sources are editable but they are also editable by users without permissions to edit. 
Should I close this issue and open a new one?

**Comment by pinarpink** [comment]
@vildead I created another [issue](https://github.com/elixir-luxembourg/daisy/issues/46 ) for permissions. we will need to wait for that one.

**Comment by vildead** [comment]
Closing the issue. Verified on commit: e593f75187cf88d0c3d7c36fc990cc920704d716
