### ISSUE TITLE
Remove unqiueness constraint on Data Declaration title

### ISSUE THREAD

**Issue by pinarpink** [elixir-luxembourg/daisy#207]
We run into this issue in real-world submissions. Data declarations may not have a unique name.

**Comment by jLebioda** [comment]
Unfortunately, I think it will not be one-liner fix (in the importer we use `DataDeclaration.objects.get(title=...` which will break once the titles are not unique); or is it irrelevant?

**Comment by vildead** [comment]
Importer will indeed need to be checked - DD should be always matched by title + owning dataset name/accession number.
