### ISSUE TITLE
Display (if possible) all attributes of entities in the Summary Box

### ISSUE THREAD

**Issue by pinarpink** [elixir-luxembourg/daisy#23]
Currently not all attributes of entities are displayed in the summary box.  All attributes values should be displayed so that the user does not have to go to an editor to see its value.

**Comment by vildead** [comment]
Of course, all attributes will not fit into summary box every time. This is solved by additional "attribute" boxes. 
I have found one attribute which still needs to be fixed (not even in any "attribute" box):

- [ ] Project - Phenotype terms

**Comment by kavitarege** [comment]
@vildead ...You can reassign it to me.. I will fix. 
Thank you

**Comment by vildead** [comment]
@kavitarege I found out that **data declaration** summary box is also missing several fields which are in its editor page. 

- [ ] Remarks on data source
- [ ] Consent status
- [ ] Remarks on data types + there is a typo in help text
- [ ] De-identification method
- [ ] Embargo date
- [ ] Storage end date - only visible from dataset page
- [ ] Description of special subjects
- [ ] Derived/re-used from
- [ ] Other restrictions

Maybe that is still under development?

**Comment by pinarpink** [comment]
@vildead  Can you be a more specific re: "Remarks on data types + there is a typo in help text"?
Cannot seem to find a typo on data type help text.
