### ISSUE TITLE
Formatting is not preserved for project lay summary

### ISSUE THREAD

**Issue by vildead** [elixir-luxembourg/daisy#234]
Sometimes, the lay summary of a project is very long (which is ok) but the new lines or paragraphs are not preserved. Everything results in one big paragraph

Also, not whole lay summary needs to be visible - it would be nice to condense the box with "Read more" on the bottom.

**Comment by jLebioda** [comment]
Solvable by using `linebreaks` filter, e.g.: `<blockquote>{{ project.description | linebreaks }}</blockquote>`
