### ISSUE TITLE
Update django-celery-results

### ISSUE THREAD

**Issue by vildead** [elixir-luxembourg/daisy#238]
dependabot failed to update `django-celery-results`
![image (1)](https://user-images.githubusercontent.com/51602017/120996189-6640cd00-c786-11eb-9cba-873b2491a469.png)

**Comment by jLebioda** [comment]
This will actually be a bit trickier, because it will involve an update of Celery, django-celery-results and django-celery-beat at the same time. Celery unfortunately has breaking changes

**Comment by jLebioda** [comment]
Turns out it was possible to find such versions that did not require any changes in codebase when upgraded.
