### ISSUE TITLE
Compact editor forms

### ISSUE THREAD

**Issue by pinarpink** [elixir-luxembourg/daisy#25]
Vertical space needs to be reduced. Also form fields can be displayed in a double column.
Scrolling to see more fields should be as minimised as possible.

**Comment by pinarpink** [comment]
Based on DAISY use sessions with research groups, this has become much more urgent. We have scroll way too much to document data declaration characteristics

**Comment by jLebioda** [comment]
Working on that on [25-compact-editor-forms](https://github.com/elixir-luxembourg/daisy/tree/25-compact-editor-forms).

Don't you think that it's less readable now?
![image](https://user-images.githubusercontent.com/32834948/73936220-9baf7f00-48e2-11ea-81df-d89a5fe4a4f8.png)

**Comment by jLebioda** [comment]
at this moment it looks like that: 
![image](https://user-images.githubusercontent.com/32834948/73942248-036bc700-48ef-11ea-9602-e6954ea69437.png)

**Comment by pinarpink** [comment]
@jLebioda   agree with you, less readable. Double columns should only be used when the two fields are closely related  e.g. start date and end date in the Project editor.  

Also we have these grey areas which wrap each field [label+input+help text], if we can minimise the margins on those that could also help. 

Another way to obtain space is to not have a 10-12 line text area for free text fields, which are often empty or contain a sentence or two.

**Comment by jLebioda** [comment]
Current: <img width="1569" alt="Screenshot 2020-04-23 at 13 24 30" src="https://user-images.githubusercontent.com/32834948/80094266-42143380-8566-11ea-97cc-877ab7bfc6ee.png">

Proposed change: <img width="1576" alt="Screenshot 2020-04-23 at 13 24 44" src="https://user-images.githubusercontent.com/32834948/80094254-3e80ac80-8566-11ea-83ea-662f09e84f87.png">

**Comment by jLebioda** [comment]
Before: 
<img width="1671" alt="Screenshot 2020-04-23 at 14 56 31" src="https://user-images.githubusercontent.com/32834948/80102108-9fae7d00-8572-11ea-9f2b-1ec0e332afb5.png">

After:
<img width="1672" alt="Screenshot 2020-04-23 at 14 56 47" src="https://user-images.githubusercontent.com/32834948/80102139-a937e500-8572-11ea-9a76-ff90831210d6.png">
