### ISSUE TITLE
Activity (log) page

### ISSUE THREAD

**Issue by jLebioda** [elixir-luxembourg/daisy#262]
**Is your feature request related to a problem? Please describe.**
Currently we don't have a very clear changes-tracking feature for all of our relevant entities (Datasets, Projects, Data declaration, Cohort, Partner, etc.). 

It would be great to see the most recent changes to these objects in one place.

**Describe the solution requested**
A single page accessible by Data Stewards and Administrators, which for a given time span (e.g. default: two weeks) will show **which user** changed **which model** - the **previous value** and the **new value**.

**Describe possible alternatives**
 * Maybe Django-admin is capable of this on its own already?
 * We have Notification system, maybe it could be used for this?

**Other info context**
There are some other small bits relevant to discussion - these below refer to complete versioning of the changes:
 * Django-revision could be used, but will be troublesome when data model changes.
 * Saving previous revisions as exported JSONs might work, but will also be problematic when data model changes
 * Having manual JSON migrations for exported files might help, but will never be 100% accurate and will alter the saved versions (so that it will be a slightly different entity than it was at the creation time)

**Comment by vildead** [comment]
I will come up with more detailed description of requirements

**Comment by jLebioda** [comment]
This might be doable by signals in models - then anything changes, an abstract entry could be created

**Comment by vildead** [comment]
requirements on OneDrive: `Data_Stewardship-R3/Tools/DAISY/requirements/issue-262_activity-log`

**Comment by vildead** [comment]
This was implemented  in 1.7.12 using AuditLog plugin. Currently it is switched on only for Access model. 

- [ ] Enable AuditLog for all models (where it makes sense)

**Comment by vildead** [comment]
Closing. The feature is in place. More development will be done in 469
