### ISSUE TITLE
Add country code to Partners

### ISSUE THREAD

**Issue by pinarpink** [elixir-luxembourg/daisy#27]
Currently there is no information in which country the Partner is located. This should be added as a field.

**Comment by vildead** [comment]
@pinarpink  sorry, but I will need at least some partner with NOT NULL country to verify this. Otherwise I am not sure that the country is mapped properly.

**Comment by pinarpink** [comment]
@vildead  you may  need to do a " pip install django-countries==5.3.3*  as set-up.py is updated with the commit that fixes this issue

**Comment by vildead** [comment]
@pinarpink once I will get permission I will close this issue. Country name (not country code though) is visible.

I had problem with indexation (celery worker was down after yesterdays redeployment). Valentin solved it:)

**Comment by pinarpink** [comment]
@vildead  Super!  thank you @neoflex for the help.

**Comment by vildead** [comment]
closing. Tested on:
develop 309fd6b620425dd4b0de0cefc23851ccb38fd97b
