### ISSUE TITLE
Display contract signatory details and allow editing

### ISSUE THREAD

**Issue by pinarpink** [elixir-luxembourg/daisy#271]
The Contract object in daisy allows recording of all signatories of the contract. The signatories section list each partner and their GDPR roles in the  activities in the project. Currently this is managed via the **Participants** section of the Contract overview page. See screenshot below.

There are a number of limitations with this section of the page:

- The listing does not show the remarks; this is a criticial section describing the activity of each partner. In short, we are unable to see the data once we enter it!!
- Also currently there is only a delete option in the listing. No possibility of edits, which makes data entry very inefficient.

![Contract-Participants](https://user-images.githubusercontent.com/2318344/128366535-198b9e4f-7efe-42a3-9d83-0694dc9d3be0.png)

**Comment by vildead** [comment]
- the **edit** option was added and is now in develop branch
