### ISSUE TITLE
Dataset importer does not link Data Declaration to Cohort

### ISSUE THREAD

**Issue by pinarpink** [elixir-luxembourg/daisy#284]
**To reproduce**

1. This could be tested with any of the DISH files we have. Export the DAISY json from the DISH file using metadata-tools. 
2. Import the file using `manage.py import_datasets`
3. You will observe that Studies/Cohorts are imported and so is the dataset, however the data declarations are not linked to the cohorts

**Expected behavior**
for each data declaration in DAISY JSON the  "source_study" denotes the name of the cohort that declaration can be linked to. This link in JSON should be taken into account by the importer.

**Comment by vildead** [comment]
It might be related to old version of json schemas used during export to JSON.  Once updated, I will retest. Locally it works now.

**Comment by vildead** [comment]
It was caused by mismatch in names of cohort (study) in JSON file.
Daisy importer logs a warning `The data declaration for the study '{safe_name}' not found.  ` in this case. 

DISH Excel exporter should throw an error in this case - I will move the issue there.
