### ISSUE TITLE
Users who do not have PI status or are not in the VIP group cannot be added alone as local custodians

### ISSUE THREAD

**Issue by barrydjenaba** [elixir-luxembourg/daisy#312]
In the form (core/forms/dataset.py), it seems that we have a custom check that verifies if there’s at least one user  is in this VIP group or have a PI status. what about project with one local custodian with others status e.g data manager, DPO etc?

**Comment by vildead** [comment]
Each project should have at least one VIP person I believe. There must be always someone legally responsible for the data. We can leave it open and discuss again once the planned permission system rework starts.

**Comment by jLebioda** [comment]
@vildead check slack conversation around 23.11.2021 please

**Comment by vildead** [comment]
The `local custodian` role might be specified more in the documentation. Also, we have local custodian for contract entity - VIP is not needed there. 

Consider also updating the form field description.
