### ISSUE TITLE
Enrich metadata of Access

### ISSUE THREAD

**Issue by jLebioda** [elixir-luxembourg/daisy#314]
**Is your feature request related to a problem? Please describe.**
Currently, the fact of User/Contact having the access to the dataset is represented using an Access model.
There are two ways of revoking the Access - deleting the object, or modifying the expiration date.
However, deletion should not be possible from the interface, and there should be some logic allowing for:
 * suspending
 * revoking
 * terminating
the accesses, with an additional reason (e.g. "User broke the contract")

**Describe the solution requested**
1. Modify the Access model to contain `Reason` free text and/or a finite set of Reasons.
2. Modify the UI and back-end logic to contain "suspend"/"rekove" and "terminate" buttons; remove "Delete" button
3. Modify the UI to show the Reason of access decision
4. Think about how history of accesses should be represented - i.e. should the box show only current accesses, and should there be a second box with a history of all accesses?

**Describe possible alternatives**
Maybe an additional subpage for history of all accesses and decisions?

**Other info context**

**Comment by jLebioda** [comment]
@vildead Do you think `Reason` (i.e. why the Access was cancelled) should be:
 * a free text OR
 * chosen from the dropdown list of all the possible reasons (with the possibility to add a new one from django admin) OR
 * chosen from the dropdown list of all the possible reasons (with the possibility to add a new one from some other place accessible to DAISY UI)
 * done in even different way?

**Comment by vildead** [comment]
- free text would require to type the reason every time
- controlled list would allow automation of the workflow

**Comment by vildead** [comment]
Specification available on OneDrive: `Data_Stewardship-R3/Tools/DAISY/requirements/issue-314_Enrich-metadata-of-access/Access-object_requirements.docx`

**Comment by vildead** [comment]
The feature was implemented in 1.7.1

Access object now has `Status` which can be 

- Pre-created
- Active
- Suspended
- Terminated

Only `Active` access objects are shown via API (e.g. read by Keycloak)
