### ISSUE TITLE
Storage entity is not exported correctly

### ISSUE THREAD

**Issue by vildead** [elixir-luxembourg/daisy#325]
The storage platform and version of data is assigned wrong keys in exported JSON. 

- [ ] fix so keys and values match
- [ ] check why schema validator did not discover this? Is the schema not restrictive enough?

![153237834-186cd0dd-a3d9-4f37-9407-725483f317d5](https://user-images.githubusercontent.com/32834948/153263307-bc81da0a-9ea1-468a-9059-597ee6162615.png)

**Comment by jLebioda** [comment]
The storage platform and version of data is assigned wrong keys in exported JSON.

 fix so keys and values match
 check why schema validator did not discover this? Is the schema not restrictive enough?

![Uploading 153237834-186cd0dd-a3d9-4f37-9407-725483f317d5.png…]()

**Comment by vildead** [comment]
the `storages` object in JSON is populated from Access instances. This is imho wrong as when there is no access registered for an existing storage (copy of the data), it is not exported. 

I suggest to add "accesses" into the schema. Storages will then list only storage locations while accesses can have a field where the storage id or name/location/details will be recorded.

**Comment by vildead** [comment]
- [ ] remove user access from the storages
- [ ] collect storages from storages not from accesses
- [ ] place accesses on the same level as storages - include link to storages
- [ ] add storage resource id in exported storages
