### ISSUE TITLE
Published datasets are displayed as non-published in dataset list

### ISSUE THREAD

**Issue by vildead** [elixir-luxembourg/daisy#335]
Published dataset has "no" under `Published` field in dataset list

![Screenshot from 2022-03-15 14-36-24](https://user-images.githubusercontent.com/51602017/158389668-b6e3c681-6a71-4c28-820d-fff74b0f4a7a.png)

**Comment by jLebioda** [comment]
I'm pretty sure that the source of the issue is in fact celery-beat not running - i.e. AFAIK the information visible on the screenshot comes from Solr, which needs indexing to reflect changes. Which instance has been impacted by the issue? Can we confirm if there's celery-beat running?

**Comment by vildead** [comment]
you are right! @jLebioda 
I have tested it on test instance and it works fine. Celery seems to be running smoothly on all instances.

Closing ;)

**Comment by jLebioda** [comment]
No problem, most likely the issue has been me (most of the times when I'm testing new stuff which requires a lot of restarts, I don't bother to restart anything aside of gunicorn/nginx) - sorry for that!
