### ISSUE TITLE
application ID in REMS is different from ID propagated to Daisy

### ISSUE THREAD

**Issue by vildead** [elixir-luxembourg/daisy#391]
e.g. in REMS and Data Catalog, the ID is `2022/1400` but in Daisy, the comment on access object is using REMS database id `"Set automatically by REMS data access request #3255"`

**Comment by vildead** [comment]
the #number is preferable as it does not contain any special characters.

**Comment by vildead** [comment]
this should propagate to both DAISY and DC

**Comment by vildead** [comment]
ensure also emails from REMS are updated (subject contains the DC ID)

**Comment by vildead** [comment]
Go with YYYY-NN as the pattern for now. 
In principle, it should be `ELU-` type of ID in future.  But for now, its enough to remove special characters and ensure its everywhere.

**Comment by jennytdtran** [comment]
The minimal requirement: the same ID should be displayed in REMS, DAISY, and Data Catalog (maybe?)

**Comment by vildead** [comment]
Closed by #526
