### ISSUE TITLE
Special subject field in data declaration shows wrong value

### ISSUE THREAD

**Issue by marikapop** [elixir-luxembourg/daisy#408]
**Describe the bug (current behaviour)**
Value of Special subject stated "yes" but displayed as "no".

**To reproduce**

1. Go to project CureMILS -> CureMILS OMICs datasets -> CureMILS: A reprogramming-based strategy for drug repositioning in patients with mitochondrial DNA-associated Leigh syndrome
2. In summary is stated "Special Subjects - no"
3. If you check real value (edit button), there "Special subjects" is "yes"

**Expected behavior**
Actual value should be displayed correctly

**Environment:**

 - Deployment: [e.g. daisy.lcsb.uni.lu]
 - Version [e.g. 1.7.11]

 
**Additional information (error logs, screenshots)**
<img width="760" alt="image" src="https://user-images.githubusercontent.com/108409595/229545792-e3e95ed7-5bc2-4322-ad1a-da0cfd197c59.png">
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/108409595/229545889-ac39f996-f18b-4838-b7e7-6ce2dc13881a.png">

Vilem already fixed it

**Comment by vildead** [comment]
fixed in 1.7.12
