### ISSUE TITLE
Support for multiple publishing channels

### ISSUE THREAD

**Issue by neoflex** [elixir-luxembourg/daisy#412]
**Is your feature request related to a problem? Please describe.**

Data stewards need the be able to select from a list of channels were the dataset or project will be published when they click on the publish button.

**Describe the solution requested**

It should be possible to register special "clients" or "dissemination channels" in Daisy. Then, when publishing a dataset or a project, Daisy would display allow the data steward to select one or several of those channels were the entity should be published.

The api endpoints for datasets and projects would only exposed the entities that have been marked as being published for the client doing the api call.

**Describe possible alternatives**

**Other info context**

**Comment by neoflex** [comment]
access to /datasets and /projects api endpoints using global api key should give  return the full list of datasets and projects, even not published

**Comment by neoflex** [comment]
- [  ] new model for endpoints (id, name: unique, api_key, [ips]) (ips if time permit) 
- [  ] new model for publication <-- find a better name (entity_id, entity_type, form_id, date, user, endpoint_id)

**Comment by nirmeen** [comment]
- [] mockup for the interface of the multiple publishing channels 
- [] create UI/Frontend model with the possibility to select a channel and corresponding form id. Add multiple channel - form_id instances. 
- [] get a list of Form_ids from REMS through /api/forms as mentioned in https://rems.lcsb.uni.lu/swagger-ui/index.html#/

**Comment by neoflex** [comment]
to get the list of form_ids from REMS, maybe it's not worth using the remsPythonClient to avoid adding an extra dependency. As it's a rather simple request it seems, maybe we should do directly using the `requests` package.

**Comment by HesamKorki** [comment]
> * [ ]  new model for endpoints (id, name: unique, api_key, [ips]) (ips if time permit)
> * [ ]  new model for publication <-- find a better name (entity_id, entity_type, form_id, date, user, endpoint_id)

@vildead asked for the feature we talked about (the link to the resource page on the endpoint). there will be a url_pattern column for the endpoint model

**Comment by HesamKorki** [comment]
- [ ] Remove the ribbon from the dataset page
- [ ] Add a field to the dataset overview called `published on:` which has chips linked to their page on the endpoint

**Comment by HesamKorki** [comment]
> > * [ ]   new model for endpoints (id, name: unique, api_key, [ips]) (ips if time permit)
> > * [ ]   new model for publication <-- find a better name (entity_id, entity_type, form_id, date, user, endpoint_id)
> 
> @vildead asked for the feature we talked about (the link to the resource page on the endpoint). there will be a url_pattern column for the endpoint model

one thing to note about this feature is, if the user does not provide the URL pattern which is optional, the chips would not be clickable

**Comment by nirmeen** [comment]
Limit the user from choosing the same endpoint twice with different forms in UI
