### ISSUE TITLE
DISH import button and scientific metadate on dataset level

### ISSUE THREAD

**Issue by marikapop** [elixir-luxembourg/daisy#418]
1) DISH import in JSON format is done via VM now. We need a function to be able to do it directly in DAISY.

2) Display scientific metadata field for dataset. No in the form of dataset creation but as separate form that can be filled by DS.

**Comment by vildead** [comment]
@marikapop can we please split this into two separate issue?(you can close this one)

 I believe the scientific metadata collection tool might be an external service and DAISY would receive only JSON (as it does now)

**Comment by marikapop** [comment]
Split into two issues #438 and #439
