### ISSUE TITLE
Add support for recording end of data processing events 

### ISSUE THREAD

**Issue by pinarpink** [elixir-luxembourg/daisy#45]
E.g. Data is archived, data is deleted. Data and results sent back to submitter etc.
(Reported by SIB)

**Comment by jLebioda** [comment]
I'd need some more information - which entity should hold this information? Or should we create a completely new model for that

**Comment by pinarpink** [comment]
Dear @jLebioda I'd say put a hold on this at the moment. I made a DAISY deployment for BIOMAP. The specific requirements will come in the following weeks or months.

**Comment by pinarpink** [comment]
We can lift the current "Transfers" section to become a more general "Data Logbook".

**Comment by pinarpink** [comment]
Done and released with https://github.com/elixir-luxembourg/daisy/commit/0f60f83c86fdbb65b3ecd06347d0de53f61e1870
