### ISSUE TITLE
Permissions not reflected to page behavior

### ISSUE THREAD

**Issue by pinarpink** [elixir-luxembourg/daisy#46]
Two issues with permissions:

* I log in as alice.white (VIP) I am not able to edit dataset sub-entities like storage or access). The view endpoints for these have the ```@permission_required('EDIT', (Dataset, 'pk', 'dataset_pk'))``` annotation.

* I log in as john.doe , he has no rights on the LCSB Human Data Survey v-1 dataset. When he goes to this dataset's overview page, he sees edit and delete buttons.

To reproduce  1. create empty database 2. migrate 3. load initial and demo data

**Comment by pinarpink** [comment]
@neoflex  vcan we add Yohan to the ELIXIR LU organisation? I was not able to assign this issue to him.

**Comment by yjarosz** [comment]
@pinarpink 
* For alice.white issue, I made a pull request that I'll mark for review
* For john.doe, it seems that he is actually `local_custodian` at the project level, so he inherits the rights to edit the dataset.

**Comment by vildead** [comment]
@pinarpink This looks much better! 
One thing: Lately I have created a dummy project and now when I want to access it, I get Server Error (500) even as the admin user. 
Newly created projects or other objects are fine. Might be issue with update procedure? Otherwise we can close this one.

**Comment by pinarpink** [comment]
@vildead  what does the log say for when you get the 500 error?

**Comment by pinarpink** [comment]
@vildead  this should work now after https://github.com/elixir-luxembourg/daisy/commit/425fc268cf69a491767617d0b4bfe5562158c988

**Comment by vildead** [comment]
@pinarpink it works on 425fc268cf69a491767617d0b4bfe5562158c988
I have another small issue:
When the user has admin privileges on a Project and none on one of the datasets in the project, the privileges are cascading - works fine. But when I try to manage permissions of the dataset, I am getting "403 Forbidden". 
Error log:
```
WARNING 2019-08-02 11:38:42,471 log 19069 140614359701312 Forbidden (Permission denied): /permissions/dataset/1/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/daisy/daisy/web/views/permissions.py", line 37, in index
    raise PermissionDenied
django.core.exceptions.PermissionDenied
WARNING 2019-08-02 11:38:42,471 log 19069 140614359701312 Forbidden (Permission denied): /permissions/dataset/1/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/daisy/daisy/web/views/permissions.py", line 37, in index
    raise PermissionDenied
django.core.exceptions.PermissionDenied
```

**Comment by yjarosz** [comment]
Spotted on #54

**Comment by pinarpink** [comment]
@vildead thank you Vil for the thorough testing. Let's discuss the cascading strategy, will probably happen post-release. cheers
