### ISSUE TITLE
Notification of users before expiry of records

### ISSUE THREAD

**Issue by vildead** [elixir-luxembourg/daisy#470]
Related to #175 #260 

Certain records do have a **date** assigned. Users shall be notified when this date is approaching. 

Existing dates (Model - field):

- Access - Expires on
- Project - project start, project end
- Data Declaration - Storage end date,Embargo date:
- Documents of projects - expiration date
- Documents of contract - expiration date

Notifications could be either **displayed in the system** or **send by email**

Users can have option to turn the notifications off or change the settings. 

Users can use the tool as task manager - option to suspend the notification or postpone it (aka select new date when the notification will be back). 

Users shall have access to the list of all (past) notifications). 

Notification shall include :
- the record issuing the notification
-  exact date which triggered it

**Comment by HesamKorki** [comment]
Divided into the following technical tasks:

- DB tables and models
- Celery Task: user loop + notification creation
- Mixin to implement the business logic of each entity to trigger notification
- Email template + Celery task to send emails
- Controllers + views

**Comment by vildead** [comment]
implemented in https://github.com/elixir-luxembourg/daisy/pull/475
