### ISSUE TITLE
Cannot create project with Institutional and National approval checkbox unchecked

### ISSUE THREAD

**Issue by vildead** [elixir-luxembourg/daisy#48]
When I try to create a new project with required fields only I will get strange "Create project" page with all drop-down lists dropped while the project is not created. 
If I check one of approval checkboxes, the project is created successfully. 
Log:
```
DEBUG 2019-07-30 15:52:58,136 utils 17787 140613281486656 search_objects query=None filter=defaultdict(<class 'list'>, {}) facets=('local_custodians', 'start_year', 'end_year', 'disease_terms', 'study_terms', 'phenotype_terms', 'gene_terms', 'has_cner', 'has_erp', 'has_legal_documents', 'funding_sources', 'company_personnel', 'contacts') model_object=<class 'core.models.project.Project'> order_by=None
WARNING 2019-07-30 15:52:58,451 log 17792 140613281486656 Not Found: /favicon.ico
WARNING 2019-07-30 15:52:58,451 log 17792 140613281486656 Not Found: /favicon.ico
WARNING 2019-07-30 15:53:16,271 log 17792 140613281486656 Not Found: /favicon.ico
WARNING 2019-07-30 15:53:16,271 log 17792 140613281486656 Not Found: /favicon.ico
```
commit 70b2bd14dde5ad864859141363d586e6ec030ca0

**Comment by pinarpink** [comment]
Hi @vildead   in case both ethics checkboxes are unchecked then you should not be able to create a Project.

You should see a validation error saying "Please enter notes on why there is no Institutional or National Ethics approval"    on both of the  "ethics approval notes" fields. Filling in one of them should be sufficient to pass the validation.

I am not able to reproduce this in my dev env, but I can reproduce the behaviour on daisy-test. We shall further investigate

**Comment by pinarpink** [comment]
@vildead  this should work now after https://github.com/elixir-luxembourg/daisy/commit/d90eaad326b6d8f6044678ee4437e9217f0cf199

**Comment by vildead** [comment]
closing the issue. Verified on commit: e593f75187cf88d0c3d7c36fc990cc920704d716
