### ISSUE TITLE
Bump python version in DEPLOYMENT.md

### ISSUE THREAD

**Issue by Fancien** [elixir-luxembourg/daisy#484]
**Is your feature request related to a problem? Please describe.**

`DEPLOYMENT.md` gives the following commands to install python:

```bash
wget https://www.python.org/ftp/python/3.9.6/Python-3.9.6.tgz
tar -xvf Python-3.9.6.tgz
cd Python-3.9.6
./configure --enable-optimizations
make
make altinstall
```

This forces the installation of Python 3.9.6, instead of the latest 3.9 version (3.9.18).

**Describe the solution requested**

Update the DEPLOYMENT.md with the commands to install the latest python 3.9 version

**Comment by vildead** [comment]
can be closed as we are switching to fully dockerized deployement
