### ISSUE TITLE
git clone issue

### ISSUE THREAD

**Issue by froggypaule** [elixir-luxembourg/daisy#497]
**Describe the bug (current behaviour)**
Cannot clone the repo 

**To reproduce**

```
plieby@dsw-demo:~$ git clone git@github.com:elixir-luxembourg/daisy.git
Cloning into 'daisy'...
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Environment:**
```
plieby@dsw-demo:~$ uname -a
Linux dsw-demo 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
 
**Additional information (error logs, screenshots)**

syslog
```
Jan 19 09:17:47 ifb017 kernel: [2578168.930933] audit: type=1400 audit(1705655867.465:2403): apparmor="ALLOWED" operation="open" profile="/usr/sbin/sssd" name="/proc/354798/cmdline" pid=354559 comm="sssd_pam" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Jan 19 09:17:47 ifb017 kernel: [2578168.931619] audit: type=1400 audit(1705655867.465:2404): apparmor="ALLOWED" operation="open" profile="/usr/sbin/sssd" name="/run/systemd/users/160670" pid=354559 comm="sssd_pam" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
```

**Comment by Fancien** [comment]
Hello!

Based on this line `ssh: connect to host github.com port 22: Connection timed out`, it may be related to github itself and not this repo in particular.

Is cloning other repositories via ssh working for you? If not, you may need to update your ssh key in your personal settings (see `https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account`)

**Comment by neoflex** [comment]
Hi, you can also try to use https instead:

```
git clone https://github.com/elixir-luxembourg/daisy.git
```

**Comment by froggypaule** [comment]
hello: indeed you are right, I can't clone anything else from github, but it is not the key: mine is still valid, plus I added another one.
So yes it is github...  
Perhaps let's wait and see. Thank you.

**Comment by froggypaule** [comment]
Good morning!
Indeed, it works this morning... no clue what could have happened. 
Thank you.
