### ISSUE TITLE
Check consistency of all tooltips with the function that the button provides

### ISSUE THREAD

**Issue by pinarpink** [elixir-luxembourg/daisy#5]
* Add dataset --> ambiguous label (Data of this project vs dataset in the "+" hint text)
* Storage location (title), data file ("+" hint)

**Comment by vildead** [comment]
looks good. Just minor comments:
 - Project page - all tooltips are in format "Add X to project" but only box for *Data of this project* has tooltip "Add **new** dataset to project"
 - Dataset page - all tooltips are in format "Add **new** X" which is not consistent with project tooltips. 
 - Partner page - tooltip on main "Edit icon" is missing

**Comment by pinarpink** [comment]
@vildead
 I tried to reflect the subtle differences in button function. Whenever a plus button immediately launches an entity creation modal the tooltip begins with "add new".  This is the case for all cards in the dataset page. In the project page, however, there are alternative ways to add things  (e.g. link existing Personnel and Contacts to the project) so I wanted to differentiate. In the future we will also be able to link existing documents and contracts to the project.  I am open to suggestions. But there is a difference.
----
I will add the "...to dataset" prefix to the dataset page tips.
Partner page, ok will do

**Comment by pinarpink** [comment]
you can re-check on https://github.com/elixir-luxembourg/daisy/commit/f9f810daefabd3b7bd4922e45eda18f9a5630d9c

**Comment by vildead** [comment]
closing the issue. Verified on commit: c4014c78bf9ee50c15a23297169d9d985da38d24
