### ISSUE TITLE
Docker Production Deployment

### ISSUE THREAD

**Issue by HesamKorki** [elixir-luxembourg/daisy#520]

**Comment by vildead** [comment]
Related to https://github.com/elixir-luxembourg/daisy/issues/298 - it was decided to go with Docker deployment for the time being. The ansible deployment code can be finalized once there is a need for it.

**Comment by vildead** [comment]
Some updates will be required to the existing code:

- bump version of postgres (as high as possible)
- deployment instructions rework
- backup instructions
	- documents - verify documents are stored in /web container under /home/daisy folder (already part of the backup)
	- logs of Celery/Nginx/Solr/...? ensure these are part of the backup

**Comment by neoflex** [comment]
+ migration procedure

**Comment by vildead** [comment]
migration steps were added in https://github.com/elixir-luxembourg/daisy/pull/521  and https://github.com/elixir-luxembourg/daisy/pull/527
