### ISSUE TITLE
Permissions editing for admin

### ISSUE THREAD

**Issue by yjarosz** [elixir-luxembourg/daisy#54]
Admin user should be able to edit permissions on dataset level.
Currently, *john.doe* is not able to edit permission on the dataset *LCSB Human Data Survey v-1* but he's local custodian

**Comment by yjarosz** [comment]
@pinarpink He is actually local custodian on project level, he should be able to edit the permissions also no?

**Comment by pinarpink** [comment]
@yjarosz  @neoflex 

 * I think per dataset or project  only the local custodians that are VIP should be able to edit permissions. 
* I do not remember why we had cascading from Project to Dataset. Imo we should not cascade. 

What do you think?

**Comment by yjarosz** [comment]
It was to set the permission on the project level if you have many datasets, it is easier to give admin access on the project level, then user would be also admin on all dataset, that's currently what we have. Only the permissions changes would have a different logic if we stay like this

**Comment by yjarosz** [comment]
Also the permission page looks weird on my deployment? only me? @pinarpink @neoflex

**Comment by pinarpink** [comment]
@yjarosz   weird in what way? it looks Ok in my dev env.

**Comment by pinarpink** [comment]
See https://github.com/elixir-luxembourg/daisy/issues/46 for steps to re-create.

**Comment by vildead** [comment]
closing the issue. Verified on commit: 12ccf4f02d13a91737e01dab3d1ff443f1bdbc8e
