### ISSUE TITLE
add version number on web pages

### ISSUE THREAD

**Issue by neoflex** [elixir-luxembourg/daisy#60]
this will help checking if the update procedure worked correctly.

**Comment by jLebioda** [comment]
Dropping some interesting links here:

How it is done in Django:
https://github.com/django/django/blob/master/django/__init__.py

The question that suggests that using version.txt/version.py is not required anymore (Python 3.8 upwards):
https://stackoverflow.com/a/58220353

And the technical means behind that:
https://docs.python.org/3.8/library/importlib.metadata.html

**Comment by jLebioda** [comment]
Oh, actually I didn't notice that the technical way is already there, in web/views/about.py
