### ISSUE TITLE
Recovery from db backup needs to be tested

### ISSUE THREAD

**Issue by pinarpink** [elixir-luxembourg/daisy#83]
Currently we backup the DAISY database via  pg_dump. We need to test if the database can be successfully restored from this dump and after restore whether application works as expected. The documentation on restore procedure also needs to be written

**Comment by vildead** [comment]
covered in MR #84

**Comment by vildead** [comment]
# #84

**Comment by pinarpink** [comment]
Fixed with https://github.com/elixir-luxembourg/daisy/commit/eb97ec8efb58f8ea932adff9d5b3f2beed7bdbe9, closing.
