### ISSUE TITLE
Unable to update the Project of a Contract

### ISSUE THREAD

**Issue by pinarpink** [elixir-luxembourg/daisy#86]
**Describe the bug (current behaviour)**
It is not possible to update the Project of a Contract. This creates great difficulty when trying to move a data set from one project to other. 

**To reproduce**
As ad admin or  legal user
1. Go to contracts
2. Select one got to its editor
3. The Project selection box is disabled.

**Expected behavior**

The contract selection box should be enabled.

**Environment:**

 - Deployment: [e.g. daisy-test.lcsb.uni.lu]
 - Version [e.g. 1.1.0]
 - Browser [e.g. Firefox 68.x]
 
 
**Additional information (error logs, screenshots)**

**Comment by vildead** [comment]
tested on: 31bc463f7d09a8821d25000b1aaf1482c3fa5286
Closing the issue
