### ISSUE TITLE
Search boxes are confusing - make them more google-like

### ISSUE THREAD

**Issue by vildead** [elixir-luxembourg/daisy#89]
**Describe the bug (current behaviour)**
Reporter: Wei Gu
Search boxes are hard to find and it is not right away obvious where to insert the searched phrase. 

**To reproduce**
Now it looks like this:
![SearchBox](https://user-images.githubusercontent.com/51602017/64611911-d1ebdf80-d3d2-11e9-82a3-a17b5b18e602.png)

**Expected behavior**
It should look like standard web search boxes (e.g. google) 
![Google Search Box](https://user-images.githubusercontent.com/51602017/64612001-0b244f80-d3d3-11e9-9fb8-5b18d29e6710.png)

**Environment:**

 - Deployment: daisy.lcsb.uni.lu
 - Version 1.1.0
 - Browser Firefox 69
 
 
**Additional information (error logs, screenshots)**

**Comment by jLebioda** [comment]
would something like that do? 

without any content inside:
![image](https://user-images.githubusercontent.com/32834948/72600321-b1e5a300-3913-11ea-91af-ce2536ca2cd9.png)

with the content:
![image](https://user-images.githubusercontent.com/32834948/72600350-bd38ce80-3913-11ea-9dba-4db4938ac8f1.png)
