### ISSUE TITLE
Field "Remarks" is missing in Dataset editor page

### ISSUE THREAD

**Issue by vildead** [elixir-luxembourg/daisy#91]
**Describe the bug (current behaviour)**
Field "Remarks" is missing in Dataset editor page even though the Dataset main panel is showing the field as empty.

**Expected behavior**
User should be able to add Remarks in Dataset editor page.

**Environment:**

 - Deployment: daisy.lcsb.uni.lu
 - Version1.1.0
 - Browser Firefox 69.0

**Comment by pinarpink** [comment]
As of release 1.2.0, this appears to be fixed. Closing.
