### ISSUE TITLE
Increase contrast on date select arrows

### ISSUE THREAD

**Issue by alexeykolodkin** [elixir-luxembourg/daisy#95]
When there is a calendar and one wants to move for later or earlier date, the arrows => and <= are not visible.
![Dates arrows](https://user-images.githubusercontent.com/55434478/65032524-9bb6de80-d943-11e9-8da1-75659ed880bd.png)

**Comment by jLebioda** [comment]
To fix, either add custom code (`color: #d9d9d9;`) inside daisy's css on `.dtp .p10 > a`,
or modify directly the library (`daisy/web/static/vendor/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css` line 28: `.dtp .p10 > a { color: #689F38; text-decoration: none; }`

**Comment by jLebioda** [comment]
Addressed in https://github.com/elixir-luxembourg/daisy/tree/95-improve-contrast-inside-calendar
however, it requires further work

**Comment by jLebioda** [comment]
Seems like it already works, and the technical problem was hidden in the docker-compose's volumes.

Once the volume with statics is removed with `docker-compose down && docker volume rm daisy_statics`, the calendar's arrows look like following: 
<img width="334" alt="Screenshot 2020-04-20 at 10 59 39" src="https://user-images.githubusercontent.com/32834948/79734072-68cc3300-82f6-11ea-92c7-f299f89ad9c0.png">
