### ISSUE TITLE
Table overflow issue inside cards

### ISSUE THREAD

**Issue by pinarpink** [elixir-luxembourg/daisy#97]
**Describe the bug (current behaviour)**
When the location definitions are too long the tables inside Storage and Access cards overflow in the dataset page.

**To reproduce**

1.  go to daisy.lcsb.uni.lu
2. search  for "Supercentenarians" dataset
3. click details
4. 

**Expected behavior**

text in table cells should be wrapped.

**Environment:**

 - Deployment: daisy.lcsb.uni.lu
 - Version  1.1.0
 - Browser Safari

 
**Additional information (error logs, screenshots)**
see attachment

![overflow](https://user-images.githubusercontent.com/2318344/65250225-884b7500-daf5-11e9-8ae8-8372663b0382.jpg)

**Comment by jLebioda** [comment]
I believe that it happens only for users that have access to edit/delete the entry

**Comment by jLebioda** [comment]
To fix, wrap the table element into `<div class="table-responsive">`

**Comment by jLebioda** [comment]
Merged to develop
