### ISSUE TITLE
Search should be remembered.

### ISSUE THREAD

**Issue by pinarpink** [elixir-luxembourg/daisy#98]
**Is your feature request related to a problem? Please describe.**

I perform a search on datasets, e.g. based on local custodian. I click on the "DETAILS" link of one of the datasets.  When I click the back button of the browser, I  get the search page without any filters. This forces the user to perform the same. search over and over.

**Describe the solution requested**
The search parameters should be remembered when the users navigates back to a search performed earlier.

**Describe possible alternatives**

**Other info context**

**Comment by neoflex** [comment]
Seems to work as expected on Safari. The URL is updated when we click on a facet or perform a keyword based search. With which browser do you face this problem?

**Comment by pinarpink** [comment]
We observed it when Patrick May was using it. We should try to reproduce on his machine. I'll let you know.

**Comment by pinarpink** [comment]
Cannot reproduce, hence closing
